### ISSUE TITLE
Won't build on 10.10.5 with Xcode 7 (unless Homebrew is used)

### ISSUE THREAD

**Issue by chdiza** [moretension/duti#15]
`duti` won't build on 10.10.5 with Xcode 7.  That seems to be because it hardcodes:

```
-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
```

but the 10.10 SDK doesn't exist in Xcode 7.  For reference, the call that fails is:

```
gcc -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 -Wall -Wmissing-prototypes -g -O2 -c ./util.c
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk'
./util.c:1:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^
1 error generated.
make: *** [util.o] Error 1
```

It _can_ be built using Homebrew, under their `superenv`, which among other things removes the `isysroot`.  (If you build in Homebrew _without_ `superenv`, a similar choke occurs.)

Here is Homebrew's summary of how it altered things, on the `clang` call in question:

```
clang called with: -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 -Wall -Wmissing-prototypes -g -O2 -c ./util.c
superenv removed:  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -Wall -Wmissing-prototypes -g -O2
superenv added:    -pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=native -mmacosx-version-min=10.10 -c ./util.c -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
```

Also, [here](https://github.com/Homebrew/homebrew/issues/44119) is the Homebrew issue report that led me to post here.

**Comment by spiffytech** [comment]
:+1:

**Comment by dickguertin** [comment]
See "duti not compatible with Yosemite" for my fixes to "configure" concerning sdk-library.
